name: numpy-tutorials
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - pandas 
  - pytest
  - nbval
  - statsmodels
  - pip
  - imageio
  - pooch
  - ffmpeg  # For gym/atari
  - pip:
    - gym[atari]==0.19
    - -r site/requirements.txt
