# See: https://circleci.com/docs/2.0/language-python/

version: 2
jobs:

  build-docs:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.8.5-buster

    steps:
      - checkout

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip wheel setuptools
            pip install -r requirements.txt
            pip install -r site/requirements.txt

      - run:
          name: Build site
          command: |
            source venv/bin/activate
            make -C site/ html

      - store_artifacts:
          path: site/_build/html

      - persist_to_workspace:
          root: site/_build
          paths: html

  deploy-docs:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.8.5-buster
    steps:
      - checkout

      - attach_workspace:
          at: site/_build

      - run:
          name: install deploy deps
          command : |
            python3 -m pip install --user ghp-import

      - run:
          name: configure git
          command: |
            git config --global user.name "ci-doc-deploy-bot"
            git config --global user.email "ci-doc-deploy-bot@nomail"
            git config --global push.default simple

      - add_ssh_keys:
          fingerprints:
            87:1a:79:b0:8f:59:c6:79:45:00:8e:9c:77:70:6f:5e

      - run:
          name: deploy to gh-pages
          command: |
            ghp-import -n -f -p -m "[skip ci] docs build of $CIRCLE_SHA1" site/_build/html


workflows:
  version: 2
  build:
    jobs:
      - build-docs
      - deploy-docs:
          requires:
            - build-docs
          filters:
            branches:
              only: master
